<?php

class ProductFlag extends ObjectModel
{
    public $background_color = '#000000';
    public $color = '#ffffff';
    public $text;
    public $active = 0;
    public $position;
    public $from;
    public $to;
    public $conditions = null;
    public $date_add;
    public $date_upd;

    public static $definition = [
        'primary' => 'id_product_flag',
        'table' => 'product_flag',
        'multishop' => false,
        'multilang' => true,
        'fields' => [
            'text' => ['type' => self::TYPE_STRING, 'validate' => 'isGenericName', 'lang' => true, 'required' => true, 'size' => 128],
            'active' => ['type' => self::TYPE_BOOL, 'validate' => 'isBool'],
            'color' => ['type' => self::TYPE_STRING, 'validate' => 'isColor'],
            'background_color' => ['type' => self::TYPE_STRING, 'validate' => 'isColor'],
            'position' => array('type' => self::TYPE_INT, 'validate' => 'isInt'),
            'conditions' => ['type' => self::TYPE_STRING],
            'from' => ['type' => self::TYPE_DATE, 'validate' => 'isDateFormat', 'required' => true],
            'to' => ['type' => self::TYPE_DATE, 'validate' => 'isDateFormat', 'required' => true],
            'date_add' => ['type' => self::TYPE_DATE, 'validate' => 'isDateFormat'],
            'date_upd' => ['type' => self::TYPE_DATE, 'validate' => 'isDateFormat'],
        ]
    ];

    public static function getFlags()
    {
        return Db::getInstance()->executeS('
            SELECT * FROM `' . _DB_PREFIX_ . 'product_flag` p
            INNER JOIN `' . _DB_PREFIX_ . 'product_flag_lang` l ON p.id_product_flag = l.id_product_flag
            AND l.id_lang = ' . (int) Context::getContext()->cookie->id_lang.'
            ORDER BY p.position ASC'
        );
    }

    public static function getProductFlagsIds($id_product)
    {
        $product_flags = Db::getInstance()->executeS('
            SELECT id_product_flag
            FROM ' . _DB_PREFIX_ . 'product_flag_product
            WHERE id_product = ' . (int)$id_product
        );


        if (!$product_flags) {
            return [];
        }

        return array_column($product_flags, 'id_product_flag');
    }

    public static function getProductFlags($id_product, $active_only = true)
    {
        $sql = '
            SELECT * FROM `' . _DB_PREFIX_ . 'product_flag_product` pf
            INNER JOIN `' . _DB_PREFIX_ . 'product_flag` p ON p.id_product_flag = pf.id_product_flag
            INNER JOIN `' . _DB_PREFIX_ . 'product_flag_lang` l ON p.id_product_flag = l.id_product_flag
            AND l.id_lang = ' . (int) Context::getContext()->cookie->id_lang . '
            AND pf.id_product = ' . (int) $id_product;

        if ($active_only) {
            $sql .= ' AND p.active = 1';
        }

        $sql .= ' ORDER BY p.position ASC';

        return Db::getInstance()->executeS($sql);
    }

    public static function saveProductFlags($id_product, $flags)
    {
        Db::getInstance()->delete('product_flag_product', 'id_product = ' . (int)$id_product);
        if (empty($flags)) {
            return;
        }
        $values = [];
        foreach ($flags as $flag) {
            $values[] = [
                'id_product' => (int)$id_product,
                'id_product_flag' => (int)$flag
            ];
        }

        Db::getInstance()->insert('product_flag_product', $values);
    }

    public function add($auto_date = true, $null_values = false)
    {
        if ($this->position <= 0) {
            $this->position = self::getHigherPosition() + 1;
        }
        return parent::add($auto_date, $null_values); // TODO: Change the autogenerated stub
    }

    public function delete()
    {
        return parent::delete() && self::cleanPositions();
    }

    public function updatePosition($way, $position, $id_product_flag = null)
    {
        if (!$id_product_flag) {
            $id_product_flag = $this->id;
        }
        $moved_product_flag = Db::getInstance()->getRow(
            'SELECT position, id_product_flag FROM '._DB_PREFIX_.'product_flag
            WHERE `id_product_flag` = '.(int)$id_product_flag.'
            ORDER BY `position` ASC'
        );

        if (!$moved_product_flag || !isset($position)) {
            return false;
        }

        return (
            Db::getInstance()->execute(
                'UPDATE `'._DB_PREFIX_.'product_flag`
            SET `position`= `position` '.($way ? '- 1' : '+ 1').'
            WHERE `position`
            '.($way
                    ? '> '.(int)$moved_product_flag['position'].' AND `position` <= '.(int)$position
                    : '< '.(int)$moved_product_flag['position'].' AND `position` >= '.(int)$position
                )
            ) && Db::getInstance()->execute(
                'UPDATE `'._DB_PREFIX_.'product_flag`
                SET `position` = '.(int)$position.'
                WHERE `id_product_flag`='.(int)$moved_product_flag['id_product_flag']
            )
        );
    }

    public static function cleanPositions()
    {
        $return = true;
        $result = Db::getInstance()->executeS('
            SELECT id_product_flag
            FROM '._DB_PREFIX_.'product_flag ORDER BY position
        ');

        $position = 0;
        foreach ($result as $value) {
            $return &= Db::getInstance()->execute(
                'UPDATE `'._DB_PREFIX_.'product_flag`
                SET `position` = '.(int)$position++.'
                WHERE `id_product_flag` = '.(int)$value['id_product_flag']
            );
        }
        return $return;
    }

    public static function getHigherPosition()
    {
        $position = DB::getInstance()->getValue('SELECT MAX(position) FROM '._DB_PREFIX_.'product_flag');
        return (is_numeric($position)) ? $position : -1;
    }
}